### PR TITLE
Update from Solr 4.5.1 to 7.7.2

### PR DESCRIPTION
**Pull request by becw**
This is blocked because of a bug with Ansible 2.9+ and the geerlingguy.solr role. Ansible is interpreting a string as a json object, but the geerlingguy.solr role is attempting to use the property as a string. The ansible docs say that it SHOULD be a string, so...

Here's the error:

> TASK [geerlingguy.solr : Ensure Solr conf directories exist.] ******************
> fatal: [default]: FAILED! => {"msg": "The conditional check 'item not in solr_cores_current.content' failed. The error was: Unexpected templating type error occurred on ({% if item not in solr_cores_current.content %} True {% else %} False {% endif %}): 'in <string>' requires string as left operand, not dict\n\nThe error appears to be in '/Users/white/repos/devkit/provisioning/roles/geerlingguy.solr/tasks/cores.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure Solr conf directories exist.\n  ^ here\n"}

### CODE REVIEW

**Comment by agentrickard** [comment]
Trying to run `make drupalbox` and I get:

`ERROR:  Error installing bundler:\n\tbundler requires RubyGems version >= 2.5.2. Try 'gem update --system' to update RubyGems itself.`

`serverspec.sh` contains this line: 

`export PATH="$PATH:/home/vagrant/.rvm/rubies/ruby-2.3.1/bin"`

Which looks like the problem. I think I can fix that in  `/vars/default/rvm.yml`

**Comment by becw** [comment]
I updated the solr config for Drupal. There are a couple of caveats for this, and I think I probably broke the serverspec tests -- but those will need to be updated anyway.

Also, I don't think there's any Solr 7 support for Drupal 7.

**Comment by agentrickard** [comment]
`Also, I don't think there's any Solr 7 support for Drupal 7.`

This would be problematic for Fed Search.

**Comment by agentrickard** [comment]
The Search API Solr page says 

`Solr 7 support is currently only working by using the Lucene 6 compatibility mode (luceneMatchVersion=6.0), though. `

So if we can add that, we should be ok.

It goes in solrconfig.xml.

```
  <!-- Controls what version of Lucene various components of Solr
       adhere to.  Generally, you want to use the latest version to
       get all bug fixes and improvements. It is highly recommended
       that you fully re-index after changing this setting as it can
       affect both how text is indexed and queried.
  -->
  <luceneMatchVersion>9.0.0</luceneMatchVersion>
```

https://lucene.apache.org/solr/guide/7_6/configuring-solrconfig-xml.html#configuring-solrconfig-xml

**Comment by becw** [comment]
Yay! I think this is ready to go.

I can merge and release like, tomorrow -- it will be version 1.5.

**Comment by becw** [comment]
The serverspec tests are now running again during the packer build, which is good. However, I'm still getting solr related failures. I can't make any sense of this! These tests pass after provisioning runs on the `dev/` vagrant, when I load the box and manually check the items that failed, they all match what the tests say they should.

Here's the short version of the failures:

```
    virtualbox-iso: rspec ./specs/solr_spec.rb:8 # File "/var/solr/data/example" should be directory
    virtualbox-iso: rspec ./specs/solr_spec.rb:12 # File "/var/solr/data/drupal8" should be directory
    virtualbox-iso: rspec ./specs/solr_spec.rb:16 # File "/var/solr/data/drupal7" should be directory
    virtualbox-iso: rspec ./specs/solr_spec.rb:20 # File "/var/solr/logs/solr.log" should be file
    virtualbox-iso: rspec ./specs/solr_spec.rb:21 # File "/var/solr/logs/solr.log" should be owned by "solr"
    virtualbox-iso: rspec ./specs/solr_spec.rb:22 # File "/var/solr/logs/solr.log" should be grouped into "solr"
```

... and here's the longer version:

```
    virtualbox-iso: Failures:
    virtualbox-iso:
    virtualbox-iso:   1) File "/var/solr/data/example" should be directory
    virtualbox-iso:      Failure/Error: it { should be_directory }
    virtualbox-iso:        expected `File "/var/solr/data/example".directory?` to return true, got false
    virtualbox-iso:        env PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH" /bin/sh -c test\ -d\ /var/solr/data/example
    virtualbox-iso:
    virtualbox-iso:      # ./specs/solr_spec.rb:8:in `block (2 levels) in <top (required)>'
    virtualbox-iso:
    virtualbox-iso:   2) File "/var/solr/data/drupal8" should be directory
    virtualbox-iso:      Failure/Error: it { should be_directory }
    virtualbox-iso:        expected `File "/var/solr/data/drupal8".directory?` to return true, got false
    virtualbox-iso:        env PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH" /bin/sh -c test\ -d\ /var/solr/data/drupal8
    virtualbox-iso:
    virtualbox-iso:      # ./specs/solr_spec.rb:12:in `block (2 levels) in <top (required)>'
    virtualbox-iso:
    virtualbox-iso:   3) File "/var/solr/data/drupal7" should be directory
    virtualbox-iso:      Failure/Error: it { should be_directory }
    virtualbox-iso:        expected `File "/var/solr/data/drupal7".directory?` to return true, got false
    virtualbox-iso:        env PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH" /bin/sh -c test\ -d\ /var/solr/data/drupal7
    virtualbox-iso:
    virtualbox-iso:      # ./specs/solr_spec.rb:16:in `block (2 levels) in <top (required)>'
    virtualbox-iso:
    virtualbox-iso:   4) File "/var/solr/logs/solr.log" should be file
    virtualbox-iso:      Failure/Error: it { should be_file }
    virtualbox-iso:        expected `File "/var/solr/logs/solr.log".file?` to return true, got false
    virtualbox-iso:        env PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH" /bin/sh -c test\ -f\ /var/solr/logs/solr.log
    virtualbox-iso:
    virtualbox-iso:      # ./specs/solr_spec.rb:20:in `block (2 levels) in <top (required)>'
    virtualbox-iso:
    virtualbox-iso:   5) File "/var/solr/logs/solr.log" should be owned by "solr"
    virtualbox-iso:      Failure/Error: it { should be_owned_by 'solr' }
    virtualbox-iso:        expected `File "/var/solr/logs/solr.log".owned_by?("solr")` to return true, got false
    virtualbox-iso:        env PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH" /bin/sh -c stat\ -c\ \%U\ /var/solr/logs/solr.log\ \|\ grep\ --\ \\\^solr\\\$
    virtualbox-iso:
    virtualbox-iso:      # ./specs/solr_spec.rb:21:in `block (2 levels) in <top (required)>'
    virtualbox-iso:
    virtualbox-iso:   6) File "/var/solr/logs/solr.log" should be grouped into "solr"
    virtualbox-iso:      Failure/Error: it { should be_grouped_into 'solr' }
    virtualbox-iso:        expected `File "/var/solr/logs/solr.log".grouped_into?("solr")` to return true, got false
    virtualbox-iso:        env PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH" /bin/sh -c stat\ -c\ \%G\ /var/solr/logs/solr.log\ \|\ grep\ --\ \\\^solr\\\$
    virtualbox-iso:
    virtualbox-iso:      # ./specs/solr_spec.rb:22:in `block (2 levels) in <top (required)>'
    virtualbox-iso:
    virtualbox-iso: Finished in 1.44 seconds (files took 0.43412 seconds to load)
    virtualbox-iso: 86 examples, 6 failures
    virtualbox-iso:
    virtualbox-iso: Failed examples:
    virtualbox-iso:
    virtualbox-iso: rspec ./specs/solr_spec.rb:8 # File "/var/solr/data/example" should be directory
    virtualbox-iso: rspec ./specs/solr_spec.rb:12 # File "/var/solr/data/drupal8" should be directory
    virtualbox-iso: rspec ./specs/solr_spec.rb:16 # File "/var/solr/data/drupal7" should be directory
    virtualbox-iso: rspec ./specs/solr_spec.rb:20 # File "/var/solr/logs/solr.log" should be file
    virtualbox-iso: rspec ./specs/solr_spec.rb:21 # File "/var/solr/logs/solr.log" should be owned by "solr"
    virtualbox-iso: rspec ./specs/solr_spec.rb:22 # File "/var/solr/logs/solr.log" should be grouped into "solr"
```

**Comment by agentrickard** [comment]
I can replicate this error.

**Comment by becw** [comment]
@agentrickard the issue is that the `vagrant` user doesn't have the `solr` group when the test is run -- but the user has that group later, when the box is booted as a vagrant environment. Sooo maybe that group isn't applied yet? Maybe packer applies a specific set of groups to the user when it runs a shell script? IDK, but this is a good start.

**Pull request merged**
